//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCadastro
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Funcionarios
    {
        public int Id { get; set; }
        public string nome { get; set; }
        public string sexo { get; set; }
        public string TELEFONE { get; set; }
        public Nullable<decimal> SALARIO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> NASCIMENTO { get; set; }
        public string CIDADE { get; set; }
        public string ESTADO { get; set; }
        public string CEP { get; set; }
    }
}
